### ISSUE TITLE
Running 'awscli-capf-refresh-data-from-cli' errors

### ISSUE THREAD

**Issue by doomchild** [sebasmonia/awscli-capf#7]
When I try to update the CLI data, I just get the following in my minibuffer:

```bash
Search failed: "^Options$"
```

And when I go look in the `*Messages*` buffer, I just see 

```bash
awscli-capf-refresh-data-from-cli: Search failed: "^Options$"
```

I'm running Emacs 26.2 on macOS Mojave (10.14.6).  If you need any other info, just let me know.

**Comment by sebasmonia** [comment]
Hi! Thanks for reporting this issue.

I have a few questions to try to understand where things went wrong:
* is `aws` the name of the CLI in your system, and is it part of the PATH?
* did it fail immediately (first attempt to get `Options`) or after a few commands?
* which version of `aws` are you using?

Like I mentioned in README, the way the documentation gets updated is not too sound. I thought scraping the website might work better but apparently they are re-styling too 🤣 

PS: hope you can get by with the included docs until we figure this out!

**Comment by doomchild** [comment]
It failed the first time I ran it.  Here's what I get when I run `aws --version`:

```bash
$ aws --version
aws-cli/1.16.190 Python/3.7.3 Darwin/18.7.0 botocore/1.12.180
```

**Comment by sebasmonia** [comment]
~I got to reproduce the issue...I tested this in my work laptop, which has Windows and then the `help` command doesn't paginate.~
~But in at home under Linux (and OSX, it seems) there's a pager. Will work on a fix.~

Like I said i hope the "canned" completion data can let you work with the package, in the meantime.

UPDATE: It's not the pager, it seems to be encoding. Running the process from Emacs I do get the full output but garbled...

**Comment by sebasmonia** [comment]
I figured out the console problems, however the format of the help from the AWS tool is completely different in Linux/OS X compared to Windows (where I developed the package).

In the meantime I submitted a fix for the recipe in MELPA to include the canned data in the download, and I will re-work the parsing to work in all three platforms equally.

**Comment by sebasmonia** [comment]
Two commits were added:

01abefa6089fe95103b14231187d9dc5a6da48f5: Parse the slightly different format of the Linux/OS X `aws help` output.
19913ed726333c666e19598b8f0fea92d18d172e: Prompt download of completion data if not present, in case parsing doesn't work
